# Generated by Django 5.0.4 on 2024-04-25 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SportsLeagueData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_id', models.CharField(max_length=100)),
                ('league_name', models.CharField(max_length=100)),
                ('league_type', models.CharField(max_length=100)),
                ('league_country', models.CharField(max_length=100)),
                ('league_season_year', models.CharField(max_length=100)),
                ('league_season_start', models.CharField(max_length=100)),
                ('league_season_end', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pp', models.CharField(max_length=50)),
            ],
        ),
    ]
