# Generated by Django 5.0.4 on 2024-04-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_api_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsleaguedata',
            name='league_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sportsleaguedata',
            name='league_season_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sportsleaguedata',
            name='league_season_start',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sportsleaguedata',
            name='league_season_year',
            field=models.DateField(),
        ),
    ]
