# Generated by Django 5.0.4 on 2024-04-26 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports_api_app', '0002_alter_sportsleaguedata_league_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SportsLeagueData',
            new_name='SportsLeagueData1',
        ),
    ]
