# Generated by Django 5.0.4 on 2024-04-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_api_app', '0003_rename_sportsleaguedata_sportsleaguedata1'),
    ]

    operations = [
        migrations.CreateModel(
            name='sportsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_id', models.IntegerField()),
                ('league_name', models.CharField(max_length=100)),
                ('league_type', models.CharField(max_length=100)),
                ('league_country', models.CharField(max_length=100)),
                ('league_season_year', models.DateField()),
                ('league_season_start', models.DateField()),
                ('league_season_end', models.DateField()),
            ],
        ),
    ]
