# Generated by Django 5.0.4 on 2024-04-26 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports_api_app', '0004_sportsdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SportsLeagueData1',
        ),
    ]
