# Generated by Django 5.0.4 on 2024-04-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_api_app', '0005_delete_sportsleaguedata1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsdata',
            name='league_season_end',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sportsdata',
            name='league_season_start',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sportsdata',
            name='league_season_year',
            field=models.CharField(max_length=100),
        ),
    ]
